name: 'GitHub Action Version Updater'
description: 'Automatically checks and updates versions of third-party actions used in your workflows'
author: 'Yuval Bo'
inputs:
  github-token:
    description: 'GitHub token for API authentication'
    required: true
  base-branch:
    description: 'The base branch on the target repo using this action'
    required: true
    default: "main"
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'refresh-cw'
  color: 'blue'
