name: "Test Action"
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      
    steps:
    - uses: actions/checkout@v3
    - name: Run the action
      uses: ./
      with:
        github-token: ${{ secrets.WORKFLOW_PAT }}
        base-branch: develop

    - name: Old version on purpose
      uses: codelytv/pr-size-labeler@v1.10.1
      with:
        xs_label: 'size/xs'
        xs_max_size: '10'
        s_label: 'size/s'
        s_max_size: '100'
        m_label: 'size/m'
        m_max_size: '500'
        l_label: 'size/l'
        l_max_size: '1000'
        xl_label: 'size/xl'
        fail_if_xl: 'false'
