name: "Generate Dist, node_mosdules and Create a PR"

on:
  workflow_dispatch:
    inputs:
      base:
        required: true
        default: 'main'
        description: "Base branch for the PR"
jobs:
  generate-dist:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # This allows the bot to push changes to the repository
      pull-requests: write

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Build with Docker
      - name: Build dist folder with Docker
        run: |
          docker build -t github-action-builder .
          chmod -R a+w node_modules
          docker run --rm -v ${{ github.workspace }}:/usr/output github-action-builder	          
        env:
          GH_TOKEN: ${{ github.token }}

      # Step 3 Create a branch, add changes, commit and push changes
      - name: Add, commit, and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"          
          git checkout -b feature/dist-upgrade-${{ github.run_id }}
          git add .
          git commit -m "Update dist and node_modules ${{ github.run_id }}"
          git push origin feature/dist-upgrade-${{ github.run_id }}

      # Step 4: Create a pull request
      - name: Create pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "Update dist/index.js and node_modules following build ${{ github.run_id }}" \
            --body "This PR updates the dist/index.js and node_modules following workflow run ${{ github.run_id }}" \
            --base "${{ github.event.inputs.base }}" \
            --head feature/dist-upgrade-${{ github.run_id }}

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
