name: "Generate Dist and Create PR"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-dist:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # This allows the bot to push changes to the repository
      pull-requests: write

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Build with Docker
      - name: Build dist folder with Docker
        run: |
          docker build -t github-action-builder .
          docker run --rm -v ${{ github.workspace }}/dist:/usr/output github-action-builder
          echo "${{ github.workspace }}/dist content is:"
          ls -la ${{ github.workspace }}/dist

      # Step 3: Commit changes if any
      - name: Commit changes
        run: |
          git checkout -b "update-dist-${{ github.run_id }}"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dist
          git commit -am "Update dist folder" || echo "No changes to commit"


      # Step 5: Create a pull request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: "update-dist-${{ github.run_id }}"
          title: "Update dist folder"
          body: "This PR updates the dist folder with the latest build output."
          labels: "Generated,Bot"
          base: main

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
