name: "Generate Dist and Create PR"

on:
  workflow_dispatch:

jobs:
  generate-dist:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # This allows the bot to push changes to the repository
      pull-requests: write

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Build with Docker
      - name: Build dist folder with Docker
        run: |
          docker build -t github-action-builder .
          chmod -R a+w node_modules
          docker run --rm -v ${{ github.workspace }}:/usr/output github-action-builder	          
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Add, commit, and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"          
          git checkout -b feature/the-pr-${{ github.run_id }}
          git add .
          git commit -m "Update dist and node_modules ${{ github.run_id }}"
          git push origin feature/the-pr-${{ github.run_id }}

      # gh pr create --base main --head "update-dist-${{ github.run_id }}" --title "Update dist and node_modules ${{ github.run_id }}" --body "Update dist and node_modules"


      # Step 4: Create a pull request
      - name: Create pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "Add files from workflow run ${{ github.run_id }}" \
            --body "This PR adds files created during workflow run ${{ github.run_id }}" \
            --base main \
            --head feature/the-pr-${{ github.run_id }}

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
