name: "Generate Dist and Create PR"

on:
  workflow_dispatch:

jobs:
  generate-dist:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # This allows the bot to push changes to the repository
      pull-requests: write

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Build with Docker
      - name: Build dist folder with Docker
        run: |
          docker build -t github-action-builder .
          chmod -R a+w node_modules
          docker run --rm -v ${{ github.workspace }}:/usr/output github-action-builder	          
          git config --global user.name 'Yuval Bo'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com>'
          git add *
          git commit -am "Update dist and node_modules ${{ github.run_id }}"
          gh pr create --base main --head "update-dist-${{ github.run_id }}" 

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
